"""remove foreignkey

迁移 ID: 9492159f98f7
父迁移: ac57f7074e58
创建时间: 2023-11-18 11:57:00.764269

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "9492159f98f7"
down_revision: str | Sequence[str] | None = "ac57f7074e58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_user_bind", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_nonebot_plugin_user_bind_original_id_nonebot_plugin_user_user",
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            "fk_nonebot_plugin_user_bind_bind_id_nonebot_plugin_user_user",
            type_="foreignkey",
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_user_bind", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_nonebot_plugin_user_bind_bind_id_nonebot_plugin_user_user",
            "nonebot_plugin_user_user",
            ["bind_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_nonebot_plugin_user_bind_original_id_nonebot_plugin_user_user",
            "nonebot_plugin_user_user",
            ["original_id"],
            ["id"],
        )

    # ### end Alembic commands ###
