"""refactor_uninfo

迁移 ID: d6e05e49f79f
父迁移: 9492159f98f7
创建时间: 2025-05-13 18:57:21.620656

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from nonebot import logger
from sqlalchemy.engine import Connection


revision: str = "d6e05e49f79f"
down_revision: str | Sequence[str] | None = "9492159f98f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


MAPPING = {
    "console": "Console",
    "discord": "Discord",
    "dodo": "DoDo",
    "feishu": "Feishu",
    "kaiheila": "Kaiheila",
    "qq": "QQClient",
    "qqguild": "QQAPI",
    "telegram": "Telegram",
    "unknown": "Unknown",
}

REV_MAPPING = {v: k for k, v in MAPPING.items()}


def get_bind_table(connection: Connection) -> sa.Table:
    return sa.Table(
        "nonebot_plugin_user_bind",
        sa.MetaData(),
        autoload_with=connection,
        resolve_fks=False,
    )


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###

    connection = op.get_bind()
    bind_table = get_bind_table(connection)
    binds = connection.execute(sa.select(bind_table.c.platform, bind_table.c.platform_id)).all()
    if len(binds) == 0:
        return
    for platform, platform_id in binds:
        if platform == "qq":
            new_platform = "QQClient" if platform_id.isdigit() else "QQAPI"
        else:
            new_platform = MAPPING.get(platform, "Unknown")
        connection.execute(
            sa.update(bind_table)
            .where(bind_table.c.platform == platform, bind_table.c.platform_id == platform_id)
            .values(platform=new_platform)
        )

    logger.info("[user] 已成功替换 bind 表中平台名称")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    bind_table = get_bind_table(connection)
    binds = connection.execute(sa.select(bind_table.c.platform, bind_table.c.platform_id)).all()
    for platform, platform_id in binds:
        connection.execute(
            sa.update(bind_table)
            .where(bind_table.c.platform == platform, bind_table.c.platform_id == platform_id)
            .values(platform=REV_MAPPING.get(platform, "unknown"))
        )
    logger.info("[bind] 已成功还原平台名称")
    # ### end Alembic commands ###
