"""add email

迁移 ID: fc352174a592
父迁移: d6e05e49f79f
创建时间: 2025-08-13 10:32:45.017672

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fc352174a592"
down_revision: str | Sequence[str] | None = "d6e05e49f79f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_user_user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_user_user", schema=None) as batch_op:
        batch_op.drop_column("email")

    # ### end Alembic commands ###
